import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PageOpening from '../components/page-opening'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import PageBody from '../components/page-body'
import PageHeading from '../components/page-heading'
import ClassQueue from '../components/class-queue'
import ClassQueueHeading from '../components/class-queue-heading'

export default function Home() {
  return (
    <div>
      <Head>
        <title>About Section</title>
        <meta name="Homepage" content="Pughub home" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>
      <Navbar/>
      <PageBody>
        <div className=' p-10 min-h-screen flex flex-col'>
          <div className=' flex-1 flex content-center max-h-10 divide-x divide-solid divide-white'>
            <div className='flex-1 text-center m-auto'>
              Captains
            </div>
            <div className='flex-1 text-center m-auto'>
              Players
            </div>
            <div className='flex-1 text-center m-auto'>
              Roles
            </div>
          </div>
          <div className='flex-1 max-h-20 my-4 ml-4 text-2xl bg-stone-800'>
            Captain
          </div>
          {/* Holds all class queue columns */}
          <div className='flex '>
            <ClassQueue>
              <ClassQueueHeading>
                <div className='p-2 flex-1'>
                  <Image src="/images/scoutemblem.png" alt="scout emblem" width={48} height={48}/ >
                </div>
                <div className='flex flex-col flex-1 mr-20 content-center'>
                  <div className=''>
                    Pocket Scout
                  </div>
                  <input className=' mb-5' type={"checkbox"}></input>
                </div>
              </ClassQueueHeading>
            </ ClassQueue>
            <ClassQueue>
              Flank Scout
            </ ClassQueue>
            <ClassQueue>
              Pocket Soldier
            </ ClassQueue>
            <ClassQueue>
              Roaming Soldier
            </ ClassQueue>
            <ClassQueue>
              Demoman
            </ ClassQueue>
            <ClassQueue>
              Medic
            </ ClassQueue>
          </div>
        </div>
        <Footer />
      </PageBody>

    </div>




    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to Pughub!
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Built with Next.js. Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}
